"use client";

import { useEffect, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, Banknote, Bell, Camera, ChevronRight, CircleHelp, CreditCard, FolderKanban, LayoutDashboard, ListPlus, LogOut, Pencil, Plus, Receipt, Settings, ShieldCheck, Sparkles, Upload, WalletCards, X } from "lucide-react";

type Project = { id: number; name: string };
type Account = { id: number; name: string; type: string; currency: string; currentBalance: number };
type Debt = { id: number; title: string; counterparty: string; direction: string; outstanding: number };
type Tx = { id?: number; title: string; project: string; category: string; date: string; amount: number; icon: string };

const seed: Tx[] = [
  { title: "咖啡豆与包装材料", project: "OCL", category: "项目支出", date: "今天 14:26", amount: -1280, icon: "O" },
  { title: "客户订单收入", project: "OCL", category: "销售收入", date: "昨天 18:10", amount: 3598, icon: "↗" },
  { title: "午餐 · 南山", project: "个人", category: "餐饮", date: "昨天 12:42", amount: -38, icon: "•" },
];
const starterProjects = ["个人", "OCL", "上班（LEBREW）", "打火机套大作战（坏苹果）", "临时"];
const money = (n: number) => `${n < 0 ? "−" : ""}¥${Math.abs(n).toLocaleString("zh-CN", { minimumFractionDigits: 2 })}`;

export default function FinanceDashboard({ displayName }: { displayName: string; email: string }) {
  const [active, setActive] = useState("总览");
  const [projects, setProjects] = useState<Project[]>(starterProjects.map((name, id) => ({ id, name })));
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [debts, setDebts] = useState<Debt[]>([]);
  const [transactions, setTransactions] = useState<Tx[]>(seed);
  const [name, setName] = useState("");
  const [amount, setAmount] = useState("");
  const [captureOpen, setCaptureOpen] = useState(false);
  const [captureNote, setCaptureNote] = useState("");
  const [editing, setEditing] = useState<Tx | null>(null);
  const [editingProject, setEditingProject] = useState<Project | null>(null);
  const [debtDirection, setDebtDirection] = useState("borrowed");
  const [counterparty, setCounterparty] = useState("");
  const [uploadCount, setUploadCount] = useState(0);
  const [uploadStatus, setUploadStatus] = useState("");
  const firstName = displayName.includes("@") ? "Fern" : displayName.split(" ")[0];

  useEffect(() => {
    fetch("/api/finance").then(r => r.ok ? r.json() : null).then(data => {
      if (!data) return;
      if (data.projects?.length) setProjects(data.projects);
      if (data.accounts) setAccounts(data.accounts);
      if (data.debts) setDebts(data.debts);
      if (data.transactions?.length) setTransactions(data.transactions.map((t: any) => ({ id: t.id, title: t.note || t.category || "未命名流水", project: "已入账", category: t.category || t.kind, date: t.transactionDate, amount: t.kind === "expense" ? -Math.abs(t.amount) : t.amount, icon: t.kind === "income" ? "↗" : "•" })));
    }).catch(() => undefined);
  }, []);

  async function addEntity(entity: "project" | "account" | "debt") {
    if (!name.trim()) return;
    const body = entity === "debt" ? { entity, title: name, counterparty: "待填写", amount: Number(amount) } : { entity, name, amount: Number(amount), type: "bank" };
    const res = await fetch("/api/finance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    if (!res.ok) return;
    const data = await res.json();
    if (data.project) setProjects(v => [...v, data.project]);
    if (data.account) setAccounts(v => [...v, data.account]);
    if (data.debt) setDebts(v => [...v, data.debt]);
    setName(""); setAmount("");
  }

  async function saveCapture() {
    const found = captureNote.match(/(\d+(?:\.\d+)?)/);
    if (!found) { setCaptureOpen(false); return; }
    const expense = /支出|支付|购买|消费|还款|付款/.test(captureNote);
    const res = await fetch("/api/finance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ amount: Number(found[1]), kind: expense ? "expense" : "income", note: captureNote, category: expense ? "待分类支出" : "待分类收入" }) });
    if (res.ok) { const data = await res.json(); if (data.transaction) setTransactions(v => [{ id: data.transaction.id, title: captureNote, project: "已入账", category: expense ? "待分类支出" : "待分类收入", date: data.transaction.transactionDate, amount: expense ? -Number(found[1]) : Number(found[1]), icon: expense ? "•" : "↗" }, ...v]); }
    setCaptureOpen(false); setCaptureNote("");
  }

  async function saveEdit() {
    if (!editing?.id) return;
    const res = await fetch("/api/finance", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editing.id, amount: Math.abs(editing.amount), note: editing.title }) });
    if (res.ok) setTransactions(v => v.map(t => t.id === editing.id ? editing : t));
    setEditing(null);
  }
  async function saveProjectEdit() { if (!editingProject) return; const res = await fetch("/api/finance", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entity: "project", id: editingProject.id, name: editingProject.name }) }); if (res.ok) setProjects(v => v.map(p => p.id === editingProject.id ? editingProject : p)); setEditingProject(null); }

  const nav = [["总览", LayoutDashboard], ["流水", Receipt], ["账户", WalletCards], ["项目", FolderKanban], ["欠款与借款", ArrowUpRight], ["报表", Banknote]] as const;
  return <div className="min-h-screen bg-[#f5f7f5] text-[#17251f]">
    <aside className="fixed inset-y-0 left-0 hidden w-[236px] flex-col border-r border-[#dce6df] bg-[#eef4ef] px-5 py-6 lg:flex">
      <Brand/><div className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-[#839b8e]">工作台</div>
      <Nav nav={nav} active={active} setActive={setActive}/><div className="mt-auto space-y-1"><button onClick={() => setActive("设置")} className="side-link"><Settings size={17}/>设置</button><a href="/signout-with-chatgpt?return_to=%2F" className="side-link"><LogOut size={17}/>退出登录</a></div>
    </aside>
    <main className="lg:pl-[236px]"><header className="flex items-center justify-between border-b border-[#e0e9e2] bg-[#f5f7f5]/90 px-5 py-4 md:px-10"><div className="flex items-center gap-3 lg:hidden"><Brand compact/></div><div className="hidden text-sm text-[#779084] lg:block">{active} <span className="mx-2 text-[#b2c0b7]">/</span> 2026年08月30日</div><div className="flex items-center gap-3"><Bell size={18} className="text-[#6d8377]"/><div className="grid h-8 w-8 place-items-center rounded-full bg-[#d9f56a] text-xs font-bold">{firstName.slice(0,1).toUpperCase()}</div><span className="hidden text-sm font-medium sm:block">{firstName}</span></div></header><div className="flex gap-1 overflow-x-auto border-b border-[#e0e9e2] bg-[#eef4ef] px-4 py-2 lg:hidden">{nav.slice(0, 5).map(([label]) => <button key={label} onClick={() => setActive(label)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs ${active === label ? "bg-[#d9f56a] font-semibold" : "text-[#60766b]"}`}>{label}</button>)}</div>
      <div className="mx-auto max-w-[1380px] px-5 py-7 md:px-10 md:py-10"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div>{active !== "总览" && <button onClick={() => setActive("总览")} className="mb-3 text-xs font-semibold text-[#78974c]">← 返回总览</button>}<p className="mb-2 text-sm text-[#779084]">你好，{firstName} <span className="text-[#d1dfd5]">/</span> 保持清醒，也保持弹性。</p><h1 className="text-3xl font-semibold tracking-[-.04em] md:text-4xl">{active}</h1></div><button onClick={() => setCaptureOpen(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[#17251f] px-4 py-3 text-sm font-semibold text-white"><Plus size={17}/>记录一笔</button></div>
        {active === "总览" ? <Overview transactions={transactions} setActive={setActive} setEditing={setEditing}/> : active === "流水" ? <TransactionList transactions={transactions} setEditing={setEditing}/> : active === "账户" ? <EntityPanel title="账户" subtitle="添加银行卡、现金、电子钱包或外币账户" placeholder="例如：招商银行、微信、现金" items={accounts} name={name} amount={amount} setName={setName} setAmount={setAmount} onAdd={() => addEntity("account")} render={a => <><b>{a.name}</b><small>{a.type} · {a.currency}</small><strong>{money(a.currentBalance)}</strong></>}/> : active === "项目" ? <EntityPanel title="项目" subtitle="个人与创业项目独立核算，项目间周转单独记录" placeholder="例如：新产品研发" items={projects} name={name} amount={amount} setName={setName} setAmount={setAmount} onAdd={() => addEntity("project")} render={p => <><b>{p.name}</b><small>活跃项目账本</small><button onClick={() => setEditingProject(p)} className="mt-3 text-xs text-[#78974c]"><Pencil size={12} className="mr-1 inline"/>编辑项目详情</button></>}/> : active === "欠款与借款" ? <DebtPanel debts={debts} name={name} amount={amount} direction={debtDirection} counterparty={counterparty} setName={setName} setAmount={setAmount} setDirection={setDebtDirection} setCounterparty={setCounterparty} onAdd={async () => { if (!name.trim() || !counterparty.trim()) return; const res = await fetch("/api/finance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entity: "debt", title: name, counterparty, amount: Number(amount), direction: debtDirection }) }); if (res.ok) { const data = await res.json(); if (data.debt) setDebts(v => [...v, data.debt]); setName(""); setAmount(""); setCounterparty(""); } }}/> : <Placeholder title={active}/>} 
      </div></main>
    {captureOpen && <Capture note={captureNote} setNote={setCaptureNote} uploadCount={uploadCount} setUploadCount={setUploadCount} status={uploadStatus} setStatus={setUploadStatus} close={() => setCaptureOpen(false)} save={saveCapture}/>} {editing && <EditBox editing={editing} setEditing={setEditing} close={() => setEditing(null)} save={saveEdit}/>} {editingProject && <ProjectEdit project={editingProject} setProject={setEditingProject} close={() => setEditingProject(null)} save={saveProjectEdit}/>}</div>;
}

function Brand({ compact = false }: { compact?: boolean }) { return <div className="mb-12 flex items-center gap-3 px-2"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#17251f] font-bold text-[#d9f56a]">F</div>{!compact && <div><div className="font-semibold">Fern Finance</div><div className="text-[10px] uppercase tracking-[.18em] text-[#779084]">quiet money clarity</div></div>}</div> }
function Nav({ nav, active, setActive }: { nav: readonly (readonly [string, any])[]; active: string; setActive: (s: string) => void }) { return <nav className="space-y-1">{nav.map(([label, Icon]) => <button key={label} onClick={() => setActive(label)} className={`side-link ${active === label ? "active" : ""}`}><Icon size={17}/>{label}</button>)}</nav> }
function Overview({ transactions, setActive, setEditing }: { transactions: Tx[]; setActive: (s: string) => void; setEditing: (t: Tx) => void }) { return <><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="总资产" value="¥86,240.60" hint="较上月 +8.4%"/><Metric label="可用现金" value="¥58,420.60" hint="个人 + 项目账户"/><Metric label="本月净现金流" value="+¥12,860" hint="收入 ¥42,680 · 支出 ¥29,820"/><Metric label="待收 / 待付" value="¥12,960" hint="2 笔待收 · 4 笔待付"/></section><section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="card p-6"><h2 className="font-semibold">现金流走势</h2><p className="mt-1 text-xs text-[#8ca196]">最近 30 天 · CNY</p><div className="mt-6 h-40 rounded-xl bg-[linear-gradient(180deg,#f7faf5,#fff)] p-3"><svg className="h-full w-full" viewBox="0 0 600 160" preserveAspectRatio="none"><path d="M0,120 C60,130 90,88 150,108 S220,125 270,78 S350,124 410,65 S500,90 600,28" fill="none" stroke="#8eaf5e" strokeWidth="4"/><path d="M0,142 C70,130 120,148 180,126 S280,145 340,126 S450,140 600,105" fill="none" stroke="#ef9b80" strokeWidth="3" strokeDasharray="6 8"/></svg></div><div className="mt-4 flex gap-5 text-xs text-[#71877b]"><span>● 收入</span><span className="text-[#d9866d]">● 支出</span></div></div><div className="card dark-card p-6"><p className="text-xs uppercase tracking-[.16em] text-[#91aa9c]">项目资金分布</p><h2 className="mt-2 text-2xl font-semibold">¥58,420.60</h2>{[["OCL",24380],["上班（LEBREW）",18600],["坏苹果",10240],["临时",5200]].map(([n,v]) => <div key={n} className="mt-5"><div className="mb-1 flex justify-between text-xs text-[#c9d8cf]"><span>{n}</span><span>¥{v.toLocaleString()}</span></div><div className="h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#d9f56a]" style={{ width: `${(v / 24380) * 48 + 12}%` }}/></div></div>)}<button onClick={() => setActive("项目")} className="mt-7 text-xs font-semibold text-[#d9f56a]">查看项目明细 <ChevronRight size={14} className="inline"/></button></div></section><section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><TransactionList transactions={transactions} setEditing={setEditing}/><div className="card p-6"><div className="flex gap-3"><div className="icon-box"><CircleHelp size={17}/></div><div><h2 className="font-semibold">本周需要核对</h2><p className="mt-1 text-sm text-[#7f745f]">周日 21:00 · 北京时间</p></div></div><div className="mt-5 space-y-3 text-sm text-[#665d4f]"><div className="flex justify-between"><span>待核对流水</span><b>6 笔</b></div><div className="flex justify-between"><span>本周净现金流</span><b className="text-[#6e9a43]">+¥3,860</b></div></div></div></section></> }
function Metric({ label, value, hint }: { label: string; value: string; hint: string }) { return <div className="card p-5"><span className="text-xs text-[#82968a]">{label}</span><div className="mt-4 text-2xl font-semibold">{value}</div><p className="mt-2 text-xs text-[#759b4a]">{hint}</p></div> }
function TransactionList({ transactions, setEditing }: { transactions: Tx[]; setEditing: (t: Tx) => void }) { return <div className="card p-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">最近流水</h2><p className="mt-1 text-xs text-[#8ca196]">点击右侧编辑即可修改</p></div></div><div className="divide-y divide-[#edf2ee]">{transactions.map((t,i) => <div key={`${t.title}-${i}`} className="flex items-center gap-3 py-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#f0f5f0] text-xs font-bold text-[#78974c]">{t.icon}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{t.title}</div><div className="mt-1 text-xs text-[#9aac9f]">{t.project} · {t.category} · {t.date}</div></div><div className="text-right"><div className={`text-sm font-semibold ${t.amount > 0 ? "text-[#6e9a43]" : "text-[#53675d]"}`}>{t.amount > 0 ? "+" : ""}{money(t.amount)}</div>{t.id && <button onClick={() => setEditing(t)} className="mt-1 text-xs text-[#78974c]"><Pencil size={11} className="mr-1 inline"/>编辑</button>}</div></div>)}</div></div> }
function EntityPanel({ title, subtitle, placeholder, items, name, amount, setName, setAmount, onAdd, render }: any) { return <div className="space-y-5"><div className="card p-6"><h2 className="font-semibold">新增{title}</h2><p className="mt-1 text-sm text-[#8ca196]">{subtitle}</p><div className="mt-5 flex flex-col gap-3 md:flex-row"><input value={name} onChange={e=>setName(e.target.value)} placeholder={placeholder} className="field flex-1"/><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="金额（可留空）" className="field md:w-40"/><button onClick={onAdd} className="rounded-xl bg-[#17251f] px-4 py-3 text-sm font-semibold text-white"><Plus size={16} className="mr-1 inline"/>添加</button></div></div><div className="card p-6"><h2 className="mb-4 font-semibold">已有记录</h2><div className="grid gap-3 md:grid-cols-2">{items.length ? items.map((item: any) => <div key={item.id} className="rounded-xl bg-[#f5f8f5] p-4">{render(item)}</div>) : <div className="col-span-full py-8 text-center text-sm text-[#8ca196]">暂无记录，请先添加。</div>}</div></div></div> }
function DebtPanel({ debts, name, amount, direction, counterparty, setName, setAmount, setDirection, setCounterparty, onAdd }: any) { return <div className="space-y-5"><div className="card p-6"><h2 className="font-semibold">新增欠款与借款</h2><p className="mt-1 text-sm text-[#8ca196]">明确记录是借入还是借出，以及对手方。</p><div className="mt-5 grid gap-3 md:grid-cols-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="事项，例如：供应商货款" className="field md:col-span-2"/><input value={counterparty} onChange={e=>setCounterparty(e.target.value)} placeholder="对手方" className="field"/><select value={direction} onChange={e=>setDirection(e.target.value)} className="field"><option value="borrowed">借入 / 我欠别人</option><option value="lent">借出 / 别人欠我</option></select><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="金额" className="field"/><button onClick={onAdd} className="rounded-xl bg-[#17251f] px-4 py-3 text-sm font-semibold text-white">添加记录</button></div></div><div className="card p-6"><h2 className="mb-4 font-semibold">已有记录</h2><div className="space-y-3">{debts.length ? debts.map((d: Debt) => <div key={d.id} className="flex items-center justify-between rounded-xl bg-[#fff8eb] p-4"><div><b>{d.title}</b><small>{d.counterparty} · {d.direction === "lent" ? "借出 / 应收" : "借入 / 应付"}</small></div><strong>{money(d.outstanding)}</strong></div>) : <div className="py-8 text-center text-sm text-[#8ca196]">暂无记录，请先添加。</div>}</div></div></div> }
function Placeholder({ title }: { title: string }) { return <div className="card p-12 text-center"><div className="icon-large"><ListPlus/></div><h2 className="mt-5 text-xl font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#81958a]">此模块正在接入实时数据。</p></div> }
function Capture({ note, setNote, uploadCount, setUploadCount, status, setStatus, close, save }: any) { return <div className="modal-backdrop"><div className="modal"><div className="flex justify-between"><div><div className="mb-2 flex items-center gap-2 text-[#799d4e]"><Sparkles size={17}/>智能录入</div><h2 className="text-2xl font-semibold">记录一笔流水</h2></div><button onClick={close}><X/></button></div><label className="upload-zone"><input type="file" multiple accept="image/*" className="hidden" onChange={e=>{const n=e.target.files?.length ?? 0; setUploadCount(n); setStatus(n ? `已加入 ${n} 张图片，等待识别` : "");}}/><Camera/><span>{uploadCount ? `已选择 ${uploadCount} 张图片` : "点击上传一张或多张图片"}</span><small>{status || "支持账单、流水、收据和付款凭证"}</small></label><textarea value={note} onChange={e=>setNote(e.target.value)} className="field mt-4 min-h-24 w-full" placeholder="例如：这笔是 OCL 购买 WING 材料，微信支付 1280 元。"/><button onClick={()=>{if(uploadCount && !note.match(/\d+(?:\.\d+)?/)) { setStatus("识别完成：没有识别出金额，请补充金额后保存"); return; } save();}} className="mt-5 w-full rounded-xl bg-[#17251f] py-3 text-sm font-semibold text-white"><Upload size={15} className="mr-2 inline"/>开始识别并保存</button></div></div> }
function EditBox({ editing, setEditing, close, save }: any) { return <div className="modal-backdrop"><div className="modal max-w-md"><div className="flex justify-between"><h2 className="text-xl font-semibold">编辑流水</h2><button onClick={close}><X/></button></div><label className="mt-6 block text-xs text-[#82968a]">备注</label><input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} className="field mt-2 w-full"/><label className="mt-4 block text-xs text-[#82968a]">金额</label><input value={Math.abs(editing.amount)} onChange={e=>setEditing({...editing,amount:Number(e.target.value) * (editing.amount < 0 ? -1 : 1)})} className="field mt-2 w-full" inputMode="decimal"/><button onClick={save} className="mt-6 w-full rounded-xl bg-[#17251f] py-3 text-sm font-semibold text-white">保存修改</button></div></div> }
function ProjectEdit({ project, setProject, close, save }: any) { return <div className="modal-backdrop"><div className="modal max-w-md"><div className="flex justify-between"><h2 className="text-xl font-semibold">编辑项目详情</h2><button onClick={close}><X/></button></div><label className="mt-6 block text-xs text-[#82968a]">项目名称</label><input value={project.name} onChange={e=>setProject({...project,name:e.target.value})} className="field mt-2 w-full"/><p className="mt-3 text-xs text-[#8ca196]">项目历史流水会保留，修改只影响项目名称。</p><button onClick={save} className="mt-6 w-full rounded-xl bg-[#17251f] py-3 text-sm font-semibold text-white">保存项目详情</button></div></div> }
