import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";
const timestamps = { createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) };
export const projects = sqliteTable("projects", { id: integer("id").primaryKey({ autoIncrement: true }), ownerEmail: text("owner_email").notNull(), name: text("name").notNull(), parentId: integer("parent_id"), status: text("status").notNull().default("active"), ...timestamps });
export const accounts = sqliteTable("accounts", { id: integer("id").primaryKey({ autoIncrement: true }), ownerEmail: text("owner_email").notNull(), name: text("name").notNull(), type: text("type").notNull().default("bank"), currency: text("currency").notNull().default("CNY"), openingBalance: real("opening_balance").notNull().default(0), currentBalance: real("current_balance").notNull().default(0), archived: integer("archived", { mode: "boolean" }).notNull().default(false), ...timestamps });
export const transactions = sqliteTable("transactions", { id: integer("id").primaryKey({ autoIncrement: true }), ownerEmail: text("owner_email").notNull(), transactionDate: text("transaction_date").notNull(), kind: text("kind").notNull(), amount: real("amount").notNull(), currency: text("currency").notNull().default("CNY"), category: text("category"), note: text("note").notNull().default(""), accountId: integer("account_id"), toAccountId: integer("to_account_id"), projectId: integer("project_id"), sourceProjectId: integer("source_project_id"), targetProjectId: integer("target_project_id"), sourceImageKey: text("source_image_key"), ...timestamps });
export const debts = sqliteTable("debts", { id: integer("id").primaryKey({ autoIncrement: true }), ownerEmail: text("owner_email").notNull(), direction: text("direction").notNull(), counterparty: text("counterparty").notNull(), title: text("title").notNull(), principal: real("principal").notNull(), outstanding: real("outstanding").notNull(), currency: text("currency").notNull().default("CNY"), dueDate: text("due_date"), status: text("status").notNull().default("open"), ...timestamps });
export const attachments = sqliteTable("attachments", { id: integer("id").primaryKey({ autoIncrement: true }), ownerEmail: text("owner_email").notNull(), transactionId: integer("transaction_id"), objectKey: text("object_key").notNull(), fileName: text("file_name").notNull(), mimeType: text("mime_type").notNull(), annotation: text("annotation").notNull().default(""), ocrStatus: text("ocr_status").notNull().default("pending"), ...timestamps });
export const settings = sqliteTable("settings", { id: integer("id").primaryKey({ autoIncrement: true }), ownerEmail: text("owner_email").notNull().unique(), weeklyReviewDay: integer("weekly_review_day").notNull().default(0), weeklyReviewTime: text("weekly_review_time").notNull().default("21:00"), baseCurrency: text("base_currency").notNull().default("CNY"), ...timestamps });
